### ISSUE TITLE
Infer Representer from Reform::Form

### ISSUE THREAD

**Issue by adrienbourgeois** [apotonick/reform#223]
I'm trying to get the Representer from a Reform::Form class but I cannot make it work. There is a class method ".representer_class" in Reform::Form but when I do something like

```ruby
SongForm.representer_class.represent(Song.first).to_hash
```

it says something like:

```
NoMethodError: undefined method `to_hash' for #<Song:...>
```

While if I define the representer manually like so

```ruby
module SongRepresenter
  include Representable::JSON
  property :title
end
```

and then I do:
```ruby
SongRepresenter.represent(Song.first).to_hash
```
it's working fine. Am I missing something?

**Comment by apotonick** [comment]
Yes, that's because the `representer_class` gives you forms. This works like a charm with Reform 2.0. Are you interested in beta-testing?

**Comment by adrienbourgeois** [comment]
Hi @apotonick , thanks for your quick answer. So I assume it's not possible to do with the current version of Reform. Could you tell me how that would be written with reform 2.0?

(I'm using reform at work so I'll wait for a stable release)

**Comment by apotonick** [comment]
There's a way you can achieve that with Reform 1.x as well. Hang on a second.

**Comment by apotonick** [comment]
BTW, are you trying to infer a representer from a contract? That's one of the key ingredients in Trailblazer (soon to be published).

**Comment by adrienbourgeois** [comment]
I'm more trying to infer a representer from a Reform:Form class (which inherits from contact I think) if that makes sense?

**Comment by apotonick** [comment]
Yeah, a Form is a Contract, so, yes. :grimacing: 

```ruby
class Disposable::Twin::Schema
  def self.from(source_class, options) # TODO: can we re-use this for all the decorator logic in #validate, etc?
    representer = Class.new(options[:superclass])
    representer.send :include, *options[:include]

    source_class.representable_attrs.each do |dfn|
      representer.property(dfn.name, dfn.instance_variable_get(:@options)) unless dfn[:extend]

      if twin = dfn[:form]
        twin = twin.evaluate(nil)

        dfn_options = dfn.instance_variable_get(:@options).merge(extend: from(twin.representer_class, options))

        representer.property(dfn.name, dfn_options)
      end
    end

    representer
  end
end

representer_class = Disposable::Twin::Schema.from(YourForm)
```

**Comment by adrienbourgeois** [comment]
It seems that I have to pass a superclass in option, not sure what I'm supposed to pass.
Also when I try

```ruby
Disposable::Twin::Schema.from(MyForm,superclass: Reform::Representer)
```

I've got an error:

```
NoMethodError: undefined method `representable_attrs' for MyForm:Class
```

Anyway thank you for your time @apotonick . I'll probably have a look at that this weekend

cheers

Ps: I had to require 'disposable/twin/schema'

**Comment by apotonick** [comment]
I updated the snippet.

**Comment by adrienbourgeois** [comment]
Still not.

```
NoMethodError: undefined method `evaluate' for #<Class:0x007fb942ff0278>
```

I don't want to waste your time, I'll keep you updated if I make it work.
Thanks man

**Comment by apotonick** [comment]
It's all good @adrienbourgeois I am actually working on this code anyway, so happy to have two pair of eyes on it! Updated the snippet, again.

**Comment by adrienbourgeois** [comment]
```
NoMethodError: undefined method `representer_class' for #<Class:0x007ff18c02a578>
```

that's from this call

```ruby
twin.representer_class
```

getting closer :P

**Comment by apotonick** [comment]
See above, more update!

**Comment by adrienbourgeois** [comment]
This

```ruby
representer_class = Disposable::Twin::Schema.from(MyForm, superclass: Representable::Decorator)
```

is now working :) But this

```ruby
representer_class.represent(Song.last).to_hash
```

is still giving me this error

```
NoMethodError: undefined method `to_hash' for #<#<Class:0x007ff18c223668>:0x007ff189cd3930>
```

Am I formatting this right?

**Comment by apotonick** [comment]
You are, but you still have to include the right engine.

```
representer_class = Disposable::Twin::Schema.from(MyForm, superclass: Representable::Decorator, include: Representable::Hash)

```

**Comment by adrienbourgeois** [comment]
It sill gives the same error

**Comment by gregory** [comment]
Awesome! First time i see git-dd :D

**Comment by apotonick** [comment]
What's git-dd? Something to drink?

**Comment by gregory** [comment]
Like git driven development :D

**Comment by apotonick** [comment]
I am using this new extensively to create representers from contracts in Reform and Trailblazer.

1. Update disposable/master.
2. Try this code (for Reform 2).

```ruby
decorator = Disposable::Twin::Schema.from(SongForm, 
  superclass: Representable::Decorator,
  representer_from: lambda { |nested| nested.twin_representer_class }
)
```

This is for Reform 1.x.

```ruby
decorator = Disposable::Twin::Schema.from(SongForm, 
  superclass: Representable::Decorator,
  representer_from: lambda { |nested| nested.representer_class }
)
```

**Comment by adrienfairfaxmedia** [comment]
Hi @apotonick , I'm back on the same issue. I'm now using reform 2.1 and I've been trying pretty hard to get a representer from a reform object.

```ruby
FormClass.representer_class
```
doesn't work anymore.

Can you tell me how to get a representer from a form object?

**Comment by apotonick** [comment]
This is how it works with Reform 2.1

```ruby
decorator = Disposable::Rescheme.from(Representer, superclass: Representable::Decorator,
  definitions_from: lambda { |nested| nested.definitions }
)
```

**Comment by adrienfairfaxmedia** [comment]
I finally defined a representer module (that uses the same form modules as my form class so it's DRYied) and this is working.

However I gave a try to your solution, I got this error:

```
NameError: undefined local variable or method `format_engine' for #<Class:0x007fc16e6c5430>
from /Users/adrien.bourgeois/.rvm/gems/ruby-2.2.4/gems/representable-3.0.0/lib/representable/cached.rb:7:in `block in build_definition'
```

**Comment by apotonick** [comment]
I updated my comment! :point_up:

**Comment by adrienfairfaxmedia** [comment]
It still doesn't work.
You code return an object of type "Class"

then I call
```
.represent(myObject)
.to_hash
```

and I have that error
```
NoMethodError: undefined method `to_hash' for #<Class:0x007ff35c6a0408>
```

**Comment by apotonick** [comment]
Can you paste form class and full exception, please? :beer:
