### ISSUE TITLE
Option :from does not work for inherited form (anymore)

### ISSUE THREAD

**Issue by thomasbaustert** [apotonick/reform#334]
Using option `:from` in form works but not in inherited form. Have to redefine the property.
Worked with Reform 1.2.6.
  
```ruby
require 'reform'

class Address
  attr_accessor :lastname

  def initialize(attrs = {})
    attrs.each_pair do |k,v|
      send("#{k}=", v)
    end
  end
end

class SuperForm < Reform::Form
  property :surname, from: :lastname

  # Needed, otherwise: undefined local variable or method `build_errors' for #<SuperForm:...
  def build_errors
  end  
end

class SubForm < SuperForm
  # redefining property works
  #property :surname, from: :lastname
end

form = SuperForm.new(Address.new(lastname: 'Doe'))
puts form.surname

# => undefined method `surname' for #<Address...
form = SubForm.new(Address.new(lastname: 'Miller'))
puts form.surname
```

**Comment by steveh** [comment]
Encountered the same error upgrading from 1.2. Here's the stack trace for easier googling, took me a while to find this issue.

```
...gems/disposable-0.2.5/lib/disposable/composition.rb:37:in `block in accessors!': undefined method `card_type' for #<struct CreditCard brand="visa"> (NoMethodError)
  from ...gems/disposable-0.2.5/lib/disposable/twin/setup.rb:42:in `read_value_for'
  from ...gems/disposable-0.2.5/lib/disposable/twin/setup.rb:38:in `setup_value_for'
  from ...gems/disposable-0.2.5/lib/disposable/twin/default.rb:4:in `setup_value_for'
  from ...gems/disposable-0.2.5/lib/disposable/twin/setup.rb:30:in `setup_property!'
  from ...gems/disposable-0.2.5/lib/disposable/twin/setup.rb:22:in `block in setup_properties!'
  from ...gems/disposable-0.2.5/lib/disposable/twin/definitions.rb:22:in `block in each'
  from ...gems/declarative-0.0.5/lib/declarative/definitions.rb:30:in `each'
  from ...gems/declarative-0.0.5/lib/declarative/definitions.rb:30:in `each'
  from ...gems/disposable-0.2.5/lib/disposable/twin/definitions.rb:16:in `each'
  from ...gems/disposable-0.2.5/lib/disposable/twin/setup.rb:22:in `setup_properties!'
  from ...gems/disposable-0.2.5/lib/disposable/twin/setup.rb:13:in `initialize'
  from ...gems/reform-2.1.0/lib/reform/contract/validate.rb:3:in `initialize'
  from ...gems/disposable-0.2.5/lib/disposable/twin/changed.rb:26:in `initialize'
  from go.rb:17:in `new'
  from go.rb:17:in `<main>'
```

**Comment by apotonick** [comment]
Yepp, I know what's the problem!

**Comment by brnrdog** [comment]
Any news about this issue? I'm having this very same problem when upgrading to 2.1

**Comment by apotonick** [comment]
I will fix it soon when I'm back from my trip. :beers:

**Comment by apotonick** [comment]
Is there any chance you could point your Gemfile to `disposable/master` and see if the problem is fixed?

```ruby
gem "disposable", github: "apotonick/disposable"
```

**Comment by steveh** [comment]
@apotonick I can't speak for OP but it doesn't work for the included example.

    .../gems/disposable-86c2b0d3e8cd/lib/disposable/expose.rb:32:in `block in accessors!': undefined method `surname' for #<Address:0x007ff8d9da6b80 @lastname="Miller"> (NoMethodError)
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/setup.rb:42:in `read_value_for'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/setup.rb:38:in `setup_value_for'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/default.rb:4:in `setup_value_for'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/setup.rb:30:in `setup_property!'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/setup.rb:22:in `block in setup_properties!'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/definitions.rb:22:in `block in each'
      from /Users/steve/.gem/ruby/2.3.0/gems/declarative-0.0.6/lib/declarative/definitions.rb:30:in `each'
      from /Users/steve/.gem/ruby/2.3.0/gems/declarative-0.0.6/lib/declarative/definitions.rb:30:in `each'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/definitions.rb:16:in `each'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/setup.rb:22:in `setup_properties!'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/setup.rb:13:in `initialize'
      from /Users/steve/.gem/ruby/2.3.0/gems/reform-2.1.0/lib/reform/contract/validate.rb:3:in `initialize'
      from .../gems/disposable-86c2b0d3e8cd/lib/disposable/twin/changed.rb:26:in `initialize'

**Comment by thomasbaustert** [comment]
@apotonick I added disposable to the Gemfile as described above but still got the same error

**Comment by apotonick** [comment]
@steveh Can you paste your form class, too?

**Comment by steveh** [comment]
Sure, here's a minimal test case:

```
require "reform"

class ParentForm < Reform::Form
  include Composition

  property :card_type, from: :brand, on: :card

  def build_errors; end
end

class ChildForm < ParentForm
end

Card = Struct.new(:brand)

card = Card.new("visa")

# works
form = ParentForm.new(card: card)

# undefined method `card_type' for #<struct Card brand="visa">
form = ChildForm.new(card: card)
```

**Comment by apotonick** [comment]
@steveh Thanks, can you update `disposable/master`, please? :heart: I think I fixed it.

**Comment by steveh** [comment]
Confirmed fixed for me as at 1884b2d. Thanks for all your work!

**Comment by thomasbaustert** [comment]
0.2.6 works for me too. Thanks!
