### ISSUE TITLE
Any way to handle accepts_nested_attributes_for-like API?

### ISSUE THREAD

**Issue by Azdaroth** [apotonick/reform#86]
Is there any neat way to handle such things as :reject_if or _destroy parameter like accepts_nested_attributes_for does?

I have some pretty ugly code to handle removing elements from collection when _destroy parameter is set (conditional validation which happens only when _destroy == "false"  and overriding #sync_models method with rejecting elements with where _destroy != "false).

My use case is: I have a form, where you can add more elements to parent model (with jquery_nested_form), the problem starts when a person e.g. by mistake clicks on "Add more" or started filling new form and decided that the item is not needed. In first case I'd like to prevent instantiating new model because all values are blank and in second case, instead of removing content from inputs, just click on "remove", which causes _destroy parameter to be set.  

I tried playing with populator but couldn't achieve anything interesting. Mixing form objects with accepts_nested_attributes_for is not a good idea and using accepts_nested_attributes_for alone is not an option (because of some virtual properties etc.). Any idea how to solve that problem in a better way?

**Comment by vala** [comment]
For the time being, I managed as @artemave to find a temporary solution by creating a module :

```ruby
module Reform
  module NestedForm
    property :id
    property :_destroy

    def _destroy=(value)
      model.mark_for_destruction if value == '1'
    end

    def sync_hash(options)
      options.exclude!([:id, :_destroy])
      super(options)
    end
  end
end
```

that I include in every Form I want to support Rails nested forms, this way

```ruby
class OrderForm < Reform::Form
  collection :items do
    include Reform::Form
    
    property :price
  end
end
```

Hope this helps others some time while you're still working on a proper solution.

Thanks !

**Comment by bkildow** [comment]
Thank you @vala! I expanded on your example for a project which I needed to reject saving a nested model if a field was blank, as well as support for the cocoon gem. I'm somewhat new at ruby, but hopefully this work around helps someone as well: https://gist.github.com/bkildow/0c1bd0db8d1e4acdbb1c.

Also, thank you @apotonick . This gem is really great!

**Comment by fernandes** [comment]
hey guys... @bkildow thank you for you gist, helped me adding support on ActiveTrail for this feature while we don't have on Reform

@apotonick if you could please help me here: https://github.com/fernandes/activetrail/blob/e84af94c43495a07d0ca0b0337bc4c5c768fefc6/spec/internal/app/models/thing.rb#L33 why its trying to change a frozen hash... I got into ActiveRecord::AutosaveAssociation but got nothing related to this

**Comment by apotonick** [comment]
This feature should be available in Reform in the next week - I almost finished preparing work in Disposable and will then make it available in Reform (adding, skipping, replacing, deleting items). :beers:

**Comment by Azdaroth** [comment]
@apotonick that's awesome!  Really been waiting for that feature :beer: :beers: .

**Comment by artemave** [comment]
@apotonick for president!

**Comment by fernandes** [comment]
@apotonick prost! :beers:

**Comment by apotonick** [comment]
Chapter 7 shows how to delete manually: https://github.com/apotonick/gemgem-trbrb/blob/chapter-7/app/concepts/thing/crud.rb#L81

However, in chapter 9 or later I will demonstrate how to use "Collection Semantics" from Representable (new upcoming feature).

**Comment by fernandes** [comment]
great!! :beers:

**Comment by christianonrails** [comment]
I tried to implement cocoon in the newest reform, but i get this error: undefined method `reflect_on_association' for MuseumForm:Class

Do I miss something?

**Comment by apotonick** [comment]
`include Reform::Form::ActiveModel::ModelReflections`. How on earth is that related to this thread?

**Comment by christianonrails** [comment]
cause cocoon was mentioned here couple of times ;)

**Comment by lucaspiller** [comment]
I know this thread has been dead for over a year, but I came across it trying to get nested forms + Cocoon working. The API for Reform 2.2 has changed quite a bit, so here is an example (based on @bkildow's) that works with Reform 2.2.1:

https://gist.github.com/lucaspiller/615f09bb525a14163921fd56b4b8e611
