### ISSUE TITLE
validates_uniqueness_of doesn't work with inline nested forms

### ISSUE THREAD

**Issue by ArthurN** [apotonick/reform#48]
``` ruby
class EmployeeForm < Reform::Form
  include Reform::Form::ActiveRecord

  property :user do
    property :email

    validates :email, presence: true
    validates_uniqueness_of :email
  end
end
```

Results in:

```
NoMethodError - undefined method `validates_uniqueness_of' for #<Class:0x007fc3c4e4bf08>:
```

I understand that `validates_uniqueness_of` comes from Reform::Form::ActiveRecord, so I tried including that in the nested form, like so:

``` ruby
class EmployeeForm < Reform::Form
  include Reform::Form::ActiveRecord

  property :user do
    include Reform::Form::ActiveRecord # <-- Trying to get uniqueness validator into here
    property :email

    validates :email, presence: true
    validates_uniqueness_of :email
  end
end
```

But that results in:

```
NoMethodError - undefined method `has_key?' for nil:NilClass:
```

So, now I'm stuck. I know this might work with v0.2.2's explicit `form: UserForm`, but I can't do that because of the issue I mentioned here: https://github.com/apotonick/reform/issues/47#issuecomment-29679676

A simple solution would be to pass on all of the stuff in Reform::Form::ActiveRecord to nested forms.
